WIP: Compose approach
gnilrets/dbt-container-skeleton pull request #13
Opened 2022-06-02 12:55 UTC by boblannon-fp

This is a slight variation on the original skeleton, which uses docker compose to provision a Postgres container that can work as a target warehouse.

2022-06-03 15:51 UTC, gnilrets requested changes
Hi @boblannon-fp.  I like the approach of using docker compose to make it simpler for users to get things set up with a postgres container.  However, the current PR breaks some existing functionality that I'd want to see fixed.  Also, I believe the README would need to be adjusted to support the new workflow?

2022-06-03 15:51 UTC, gnilrets commented on tasks.py
> +    )
The `ci` flag was used in the github actions workflow to speed up testing so it didn't have to completely rebuild the container image every time.  I'd like to keep that.

2022-06-03 15:51 UTC, gnilrets commented on tasks.py
> -    envs_arg = ' '.join(['--env ' + env for env in envs])
Why did this need to change?

2022-06-03 15:51 UTC, gnilrets commented on tasks.py
> -def docker_run_dbt_cmd(command, interactive=False, docker_args=''):
This method is still used elsewhere so it can't be removed.

2022-06-10 10:13 UTC, boblannon-fp commented
> Hi @boblannon-fp. I like the approach of using docker compose to make it simpler for users to get things set up with a postgres container. 

Thanks! As noted, it's just a WIP, wanted to see what you thought of the general idea.  Feel free to close it if you'd rather not have a draft PR hanging around.

> However, the current PR breaks some existing functionality that I'd want to see fixed.

I will look into this, but probably not very soon.  If anyone would like to branch off of this and try something different, by all means, have at it!

> Also, I believe the README would need to be adjusted to support the new workflow?

Yes, definitely.

2023-10-13 06:40 UTC, closed without merging